### ISSUE TITLE
Same dev and test data in sst_data for classification task

### ISSUE THREAD

**Issue by WildeLau** [leuchine/S-LSTM#1]
I found that the sst_data for classification task has same dev and test data. I wonder if you are randomly split the dev data from train data in your work? Thank you!

**Comment by leuchine** [comment]
Hi @WildeLau :

Sorry for the confusion. The original data set did not contain dev set. As a result, the dev data in my folder is just a placeholder. I have another program, which is used for splitting. The file is uploaded (split_dev.py). Please use this file for randomly splitting _trn file into _trn and _dev files. I also updated the sst_data files. Hope this help. Thank you very much.

Best Regards,
Qi

**Comment by WildeLau** [comment]
@leuchine thanks for your kindness. This helps a lot!
