### ISSUE TITLE
notation confusion

### ISSUE THREAD

**Issue by speedcell4** [leuchine/S-LSTM#2]
https://github.com/leuchine/S-LSTM/blob/master/sequence_tagging/model/ner_model.py#L277

in this line, you defined a separate parameter for $\mathbf{g}_{t-1}$, does this mean the $W_f$ in equation (3) is not the same parameter $W_f$ in equation (2), though you are utilizing the same notations?
same question for $U_f, W_o, U_o, b_f, b_o$ in both of these two equations.

thx~

**Comment by leuchine** [comment]
Hi:

Thanks for your interests. Yes. Here is a bit abuse of notations.  The sentence node uses a different set of parameters as the word nodes, since the 'dynamics'/representations are different in sentence node and word nodes.  Thanks!

Best Regards,
Qi

**Comment by speedcell4** [comment]
thanks~
I have not run your code yet, does the default hyperparameters can reproduce the numbers in your paper? actually, I only care about the NER part.

**Comment by leuchine** [comment]
Yes. The default parameters should work. A bit fine-tuning might be needed. I recall that the F1 varies from 91.4 - 91.70. Thanks!

Best Regards,
Qi

**Comment by speedcell4** [comment]
thank you so much~
